### ISSUE TITLE
NewSocketTransaction: faucet error: 22h42m17.295s left until next allowance

### ISSUE THREAD

**Issue by cavinpabua** [kewka/give-me-bnb#3]
`docker run --rm kewka/give-me-bnb give-me-bnb -proxy socks5://127.0.0.1:9050 -to <address>`

it seems like the built-in Tor socket is not working?

**Comment by kewka** [comment]
Tor has a limited number of exit nodes (https://check.torproject.org/torbulkexitlist). I think a lot of people use this proxy. You can use any other proxy list.

Example with [proxy-lists](https://www.npmjs.com/package/proxy-lists) (node.js):
```sh
$ npm i -g proxy-lists
$ proxy-lists getProxies --stdout --protocols="socks5" | while read proxy; do docker run --rm kewka/give-me-bnb give-me-bnb -to <address> -proxy "socks5://$proxy"; done
```

**Comment by cavinpabua** [comment]
> Tor has a limited number of exit nodes (https://check.torproject.org/torbulkexitlist). I think a lot of people use this proxy. You can use any other proxy list.
> 
> Example with [proxy-lists](https://www.npmjs.com/package/proxy-lists) (node.js):
> 
> ```shell
> $ npm i -g proxy-lists
> $ proxy-lists getProxies --stdout --protocols="socks5" | while read proxy; do docker run --rm kewka/give-me-bnb give-me-bnb -to <address> -proxy "socks5://$proxy"; done
> ```

Thanks man @kewka . It's working like a charm!
