### ISSUE TITLE
bypass captcha

### ISSUE THREAD

**Issue by tuyulbossq01** [kewka/give-me-bnb#6]
can you update it using anti-captcha or anycaptcha ?

**Comment by tuyulbossq01** [comment]
great !! it's work right now. thanks

**Comment by Jaskaran546** [comment]
@kewka i am not able to run the comman do we need to enter our private key like this 
$ docker run --rm kewka/give-me-bnb:hcaptcha give-me-bnb -key 7hsfjksfdsfkjsfh 
or like this 
$ docker run --rm kewka/give-me-bnb:hcaptcha give-me-bnb -key <7hsfjksfdsfkjsfh>
if i try the first one it goes on infinite loop like this 
![Screenshot from 2022-05-30 10-02-38](https://user-images.githubusercontent.com/96573171/170917654-bdc9c112-70a8-49fa-87b5-f215a3d1d207.png)

**Comment by kewka** [comment]
> @kewka i am not able to run the comman do we need to enter our private key like this $ docker run --rm kewka/give-me-bnb:hcaptcha give-me-bnb -key 7hsfjksfdsfkjsfh or like this $ docker run --rm kewka/give-me-bnb:hcaptcha give-me-bnb -key <7hsfjksfdsfkjsfh> if i try the first one it goes on infinite loop like this ![Screenshot from 2022-05-30 10-02-38](https://user-images.githubusercontent.com/96573171/170917654-bdc9c112-70a8-49fa-87b5-f215a3d1d207.png)

@Jaskaran546 

1) What shell do you use? Try passing your key with `--key 7hsfjksfdsfkjsfh` or `--key=7hsfjksfdsfkjsfh` 
2) `7hsfjksfdsfkjsfh` doesn't look like a valid private key. You'll get an error like this `blockchain.ReadAccount: invalid hex character 'h' in private key`

**Comment by TripleD1337** [comment]
> I added [hcaptcha-challenger](https://github.com/QIN2DIM/hcaptcha-challenger) in [b3f01c4](https://github.com/kewka/give-me-bnb/commit/b3f01c493c817c79dab3db7546933180d8722c39) and pushed the `kewka/give-me-bnb:hcaptcha` docker image. It doesn't work on my mac m1 (`arm64`), but it works on windows or linux. Could you try this?
> 
> ```shell
> $ docker run --rm kewka/give-me-bnb:hcaptcha give-me-bnb -key <your private key>
> ```

They changed something @kewka. Currently I am getting this error:

`captcha.New: CAPTCHA_RESPONSE not found`

**Comment by kewka** [comment]
> > I added [hcaptcha-challenger](https://github.com/QIN2DIM/hcaptcha-challenger) in [b3f01c4](https://github.com/kewka/give-me-bnb/commit/b3f01c493c817c79dab3db7546933180d8722c39) and pushed the `kewka/give-me-bnb:hcaptcha` docker image. It doesn't work on my mac m1 (`arm64`), but it works on windows or linux. Could you try this?
> > ```shell
> > $ docker run --rm kewka/give-me-bnb:hcaptcha give-me-bnb -key <your private key>
> > ```
> 
> They changed something @kewka. Currently I am getting this error:
> 
> `captcha.New: CAPTCHA_RESPONSE not found`

Fixed in [f612495](https://github.com/kewka/give-me-bnb/commit/f612495c55fd9f201409dc4f143bdfdefcff9293). Pull the docker image (`docker pull kewka/give-me-bnb:hcaptcha`) and try again

**Comment by Jaskaran546** [comment]
> docker pull kewka/give-me-bnb:hcaptcha
yeah that was not a private key i just typed few words currently i am using this command $ sudo docker run --rm kewka/give-me-bnb:hcaptcha sh -c "while :; do give-me-bnb -proxy socks5://127.0.0.1:9050 -key <privatekey>; killall -HUP tor; done"

One more thing can we use this to get eth also ?

**Comment by kewka** [comment]
> > docker pull kewka/give-me-bnb:hcaptcha
> > yeah that was not a private key i just typed few words currently i am using this command $ sudo docker run --rm kewka/give-me-bnb:hcaptcha sh -c "while :; do give-me-bnb -proxy socks5://127.0.0.1:9050 -key ; killall -HUP tor; done"
> 
> One more thing can we use this to get eth also ?

Yes, use the `-currency` parameter ([possible values](https://github.com/kewka/give-me-bnb/blob/f612495c55fd9f201409dc4f143bdfdefcff9293/internal/faucet/currency.go#L18)).

**NOTE: You need BNB in your account to pay for gas fees.**

**Comment by hand-token** [comment]
@kewka is it possible to define the rpc where the collecting transaction is made against?

**Comment by TripleD1337** [comment]
@kewka I am not able to create a PR from the source repo of the hcaptcha challange to your fork to update it again.

> captcha.New: CAPTCHA_RESPONSE not found

happening again.

**Comment by Terrence9292** [comment]
always CAPTCHA_RESPONSE not found.

**Comment by Terrence9292** [comment]
@kewka always CAPTCHA_RESPONSE not found

**Comment by heycryptobob** [comment]
I'm also getting `captcha.New: CAPTCHA_RESPONSE not found`. Any update?

**Comment by erocoder01** [comment]
Hey kewka, i am also getting this error: captcha.New: CAPTCHA_RESPONSE not found.

**Comment by kewka** [comment]
Hey, I've updated it 🙂
Pull the image (`docker pull kewka/give-me-bnb:hcaptcha`) and try again please. It still doesn't work on m1 (arm64).
